Controllers/CardController.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyLibrary.Models;

namespace MyLibrary.Controllers
{
    [AuthorizeWithSession]
    public class CardController : Controller
    {
        //
        // GET: /Card/
        public ActionResult Index()
        {
            JObject user = GetUser();
            ViewBag.Message = Request.QueryString["message"];
            return View(user);
        }

        [HttpPost]
        public ActionResult Index(UserViewModel formUser)
        {
            JObject user = GetUser();
            user["first_name"] = formUser.first_name;
            user["last_name"] = formUser.last_name;

            JObject updateduser = UpdateUser(user);
            ViewBag.Message = "Your details were updated successfully.";
            return View(updateduser);
        }

        private JObject GetUser()
        {
            var json = Utils.AlmaApiGet("/users/" + Session["email"]);
            JObject user = JsonConvert.DeserializeObject<JObject>(json);
            return user;
        }

        private JObject UpdateUser(JObject user)
        {
            var json = Utils.AlmaApiPut("/users/" + Session["email"], user.ToString());
            JObject newuser = JsonConvert.DeserializeObject<JObject>(json);
            return user;
        }
	}
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My Alma Library</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("My Alma Library", "Index", "Home", null, new { @class = "brand" })
                <div class="nav-collapse collapse">
                    <ul class="nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("My Library Card", "", "Card")</li>
                        <li>@Html.ActionLink("Requests", "", "Requests")</li>
                        <li>@Html.ActionLink("Rooms", "", "Rooms")</li>
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My Alma Library</p>
            <small>Home page image &copy; University of St. Thomas</small>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>